@url = http://localhost:5056

POST {{url}}/api/products/
Content-Type: application/json

{
  "name": "string",
  "description": "string",
  "stock": 0,
  "price": 0,
  "imageUrl": "string",
  "discountPrice": 0,
  "categoryId": "hehe",
  "brandId": 0,
  "sku": "string"
}


###